version: '3.7'

services:
  server:
    container_name: gd-recursos-humanos-api
    entrypoint: [ "sh", "-c", "java -cp app:app/lib/* br.com.geradordedevs.gdrecursoshumanos.SistemaDeGestaoDeRecursosHumanosApplication" ]
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: gd-recursos-humanos-db
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=db_gd_recursos_humanos
      - MYSQL_USER=recursos
      - MYSQL_PASSWORD=123456
    ports:
      - '3306:3306'
    volumes:
      - ./data/db:/data/db


